apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: v1-service
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/app_dccn_dmmgr:latest
        imagePullPolicy: Always
        command: [
          "./shippy-v1-service",
          "--selector=static",
          "--server_address=:8080"
        ]
        env:
        - name: DB_HOST
          value: "mongo:27017"
        ports:
        - containerPort: 8080
          name: v1-port
