version: 2
jobs:
  build:
    docker:
      # Build in Python container to install AWS CLI
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Ankr-network/dccn-appmgr
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: copy ssh key
          command: |
            cp ${HOME}/.ssh/id_rsa id_rsa
      - run:
          name: Install AWSCLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region us-west-2)
      - run:
          name: Install Kops and Kubectl
          command: |
            wget -O kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
            chmod +x ./kops
            sudo mv ./kops /usr/local/bin/kops
            wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: "Build & Push Docker Image"
          command: |
            set -x

            BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
            SHA1_SHORT=$(git rev-parse --short HEAD)
            DATE=`date +%Y%m%d%H%M%S`
            if [[ ($BRANCH_NAME == "develop") ]]
            then
              BRANCH_NAME="dev"
              K8S_CLUSTER="stage.hub"
              CHARTMUSEUM_URL="http://chart-stage.dccn.ankr.com:8080"
            elif [[ ($BRANCH_NAME == "master") ]]
            then
              BRANCH_NAME="stage"
              K8S_CLUSTER="hub"
              CHARTMUSEUM_URL="http://chart.dccn.ankr.com:8080"
            else
              BRANCH_NAME="feat"
              K8S_CLUSTER="dev.hub"
              CHARTMUSEUM_URL="http://chart-dev.dccn.ankr.com:8080"
            fi

            dep ensure --vendor-only 

            docker build --no-cache --build-arg CHARTMUSEUM_URL=${CHARTMUSEUM_URL}  -f dockerfile/app.Dockerfile -t dccn-appmgr:$BRANCH_NAME .
            for TAG in $BRANCH_NAME $SHA1_SHORT $BRANCH_NAME$DATE; do
              docker tag dccn-appmgr:$BRANCH_NAME $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/dccn-appmgr:$TAG
              docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/dccn-appmgr:$TAG
            done
            
            kops export kubecfg --name ${K8S_CLUSTER}.k8s.ankr.network --state s3://kops.${K8S_CLUSTER}.config
            
            kubectl set image dccn-appmgr=$AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/dccn-appmgr:${BRANCH_NAME}${DATE} --local -f kubernetes/app.yml -o yaml > kubernetes/app_patch.yml
            kubectl set image dccn-appmgr=$AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/dccn-appmgr:${BRANCH_NAME}${DATE} --local -f kubernetes/app_test.yml -o yaml > kubernetes/app_test_patch.yml
            kubectl apply -f kubernetes/app_patch.yml
            if ! kubectl rollout status deploy/appmgr --watch=true --timeout=60s; then
              echo "Deploy failed, roll back to previous version"
              kubectl rollout undo deploy/appmgr 
            fi
            kubectl apply -f kubernetes/app_svc.yml
            sleep 30
            if kubectl get job appmgr-test; then
              kubectl delete job appmgr-test
            fi
            kubectl apply -f kubernetes/app_test_patch.yml
            
